import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarToggler } from "./_components/navbarComponent/navbar";
import Footer from "./_components/footerComponent/footer";
import StoreProvider from "./_components/reduxProviderComponent/storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MovieHaven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <StoreProvider>
          <NavbarToggler />
          {children}
        </StoreProvider>
        <Footer />
      </body>
    </html>
  );
}
